### ISSUE TITLE
Why does this require your resolve role?

### ISSUE THREAD

**Issue by t2d** [drew-kun/ansible-rpi_expandfs#1]
This was unexpected to me and doesn't seem like a hard dependency. Or am I missing something?

**Comment by drew1kun** [comment]
You are right! it actually does not need this anymore. The reason why I have added it is because I have tested it on my pihole, which was acting as a dns resolver for itself, and did not always work properly. I will have to remove it. Thank you very much for letting me know. I did not even think that someone except me will ever try to use it, lol
